### ISSUE TITLE
リンクが開かない

### ISSUE THREAD

**Issue by liquorwell36** [liquorwell36/qiitaapp#18]
記事内のリンクテキスト表示はされているが、リンク先に遷移しない。
html表示させるためにパッケージを使ったと思うので、調べればできると思う。

**Comment by liquorwell36** [comment]
やっぱりflutter_htmlというパッケージを使っていた。
https://pub.dev/packages/flutter_html
```
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_html: ^2.2.1
```
